env:
  es2021: true
  node: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides:
  [
    {
      files: ['./test/*'],
      env: { jest: true },
      plugins: ['jest'],
      rules:
        {
          'jest/no-disabled-tests': 'warn',
          'jest/no-focused-tests': 'error',
          'jest/no-identical-title': 'error',
          'jest/prefer-to-have-length': 'warn',
          'jest/valid-expect': 'error',
          'jest/prefer-expect-assertions': 'error',
          '@typescript-eslint/no-empty-function': 'off',
          'quotes': 'off',
        },
    },
  ]
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules:
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  '@typescript-eslint/no-unused-vars': error
  '@typescript-eslint/interface-name-prefix': 'off'
  '@typescript-eslint/explicit-module-boundary-types': 'off'
